### ISSUE TITLE
Stream stdout and stderr from subprocess processes.

### ISSUE THREAD

**Issue by jcozar87** [demosense/demorepo#12]
Right now the subprocess run a shell process and return the stdout and stderr at the end of the execution.

It is useful to stream such information in real time.

**Comment by jacintoArias** [comment]
We should also indicate the current project like:

```
-------------------------
Entering projectA

Running stage xxx:
STDOUT:
   <stdout>
STDERR:
   <stderr>
-------------------------
```

**Comment by jacintoArias** [comment]
It would be nice to have an additional parameter to run silently and to print the output to a searchable log. (at least one file for stdout and stderr)

By searchable I mean: Create unique index to identify the section of each project log i.e:

```
Log-Proj-x
```

**Comment by jcozar87** [comment]
I agree. Indeed, we should use the package logging, and use standard log levels, handlers (stdout or files), etc.
