### ISSUE TITLE
Print a summary of operations

### ISSUE THREAD

**Issue by jacintoArias** [demosense/demorepo#16]
The tool should print a summary at the end of the operations. Something like:

```
Demorepo finished for stage xxxx. N scripts runned succesfully. 2 Errors occurred.
- Failed scripts:
   - Proj x failed for stage n
   - Proj y failed for stage n
```

**Comment by jcozar87** [comment]
We should create a module to manage the information which is printed right now.

This way, we can standardise the messages, format, and so on.
