### ISSUE TITLE
Include a project order to run stages 

### ISSUE THREAD

**Issue by jcozar87** [demosense/demorepo#9]
In demorepo-config.yml include a in projects a field `order`, which is a list of projects whose stages will be executed in such order. Projects not in such list will be executed in an arbitrary order (by name).

**Comment by jacintoArias** [comment]
@jcozar87  can we close this? It seems to be resolved already

**Comment by jcozar87** [comment]
I agree. Order is implemented (if we need to include dependencies it is a different feature).
